INSERT INTO style(styleType) VALUES("Ordinary Bitter");
INSERT INTO style(styleType) VALUES("Special Bitter or Best Bitter");
INSERT INTO style(styleType) VALUES("Extra Special Bitter");
INSERT INTO style(styleType) VALUES("Scottish-Style Light Ale");
INSERT INTO style(styleType) VALUES("Scottish-Style Heavy Ale");
INSERT INTO style(styleType) VALUES("Scottish-Style Export Ale");
INSERT INTO style(styleType) VALUES("English-Style Summer Ale");
INSERT INTO style(styleType) VALUES("Classic English-Style Pale Ale");
INSERT INTO style(styleType) VALUES("English-Style India Pale Ale");
INSERT INTO style(styleType) VALUES("Strong Ale");
INSERT INTO style(styleType) VALUES("Old Ale");
INSERT INTO style(styleType) VALUES("English-Style Pale Mild Ale");
INSERT INTO style(styleType) VALUES("English-Style Dark Mild Ale");
INSERT INTO style(styleType) VALUES("English-Style Brown Ale");
INSERT INTO style(styleType) VALUES("Brown Porter");
INSERT INTO style(styleType) VALUES("Robust Porter");
INSERT INTO style(styleType) VALUES("Sweet Stout or Cream Stout");
INSERT INTO style(styleType) VALUES("Oatmeal Stout");
INSERT INTO style(styleType) VALUES("Scotch Ale");
INSERT INTO style(styleType) VALUES("British-Style Imperial Stout");
INSERT INTO style(styleType) VALUES("British-Style Barley Wine Ale");
INSERT INTO style(styleType) VALUES("Irish-Style Red Ale");
INSERT INTO style(styleType) VALUES("Classic Irish-Style Dry Stout");
INSERT INTO style(styleType) VALUES("Export-Style Stout");
INSERT INTO style(styleType) VALUES("Golden or Blonde Ale");
INSERT INTO style(styleType) VALUES("American-Style Amber/Red Ale");
INSERT INTO style(styleType) VALUES("American-Style Pale Ale");
INSERT INTO style(styleType) VALUES("Juicy or Hazy Pale Ale");
INSERT INTO style(styleType) VALUES("American-Style Strong Pale Ale");
INSERT INTO style(styleType) VALUES("Session India Pale Ale");
INSERT INTO style(styleType) VALUES("American-Style India Pale Ale");
INSERT INTO style(styleType) VALUES("Juicy or Hazy India Pale Ale");
INSERT INTO style(styleType) VALUES("Pale American-Belgo-Style Ale");
INSERT INTO style(styleType) VALUES("Dark American-Belgo-Style Ale");
INSERT INTO style(styleType) VALUES("American-Style Brown Ale");
INSERT INTO style(styleType) VALUES("American-Style Black Ale");
INSERT INTO style(styleType) VALUES("American-Style Stout");
INSERT INTO style(styleType) VALUES("American-Style Imperial Porter");
INSERT INTO style(styleType) VALUES("American-Style Imperial Stout");
INSERT INTO style(styleType) VALUES("Double Hoppy Red Ale");
INSERT INTO style(styleType) VALUES("Imperial Red Ale");
INSERT INTO style(styleType) VALUES("American-Style Imperial or Double India Pale Ale");
INSERT INTO style(styleType) VALUES("Juicy or Hazy Imperial or Double India Pale Ale");
INSERT INTO style(styleType) VALUES("American-Style Barley Wine Ale");
INSERT INTO style(styleType) VALUES("American-Style Wheat Wine Ale");
INSERT INTO style(styleType) VALUES("Smoke Porter");
INSERT INTO style(styleType) VALUES("American-Style Sour Ale");
INSERT INTO style(styleType) VALUES("German-Style Koelsch");
INSERT INTO style(styleType) VALUES("German-Style Altbier");
INSERT INTO style(styleType) VALUES("Kellerbier or Zwickelbier Ale");
INSERT INTO style(styleType) VALUES("Berliner-Style Weisse");
INSERT INTO style(styleType) VALUES("Leipzig-Style Gose");
INSERT INTO style(styleType) VALUES("Contemporary-Style Gose");
INSERT INTO style(styleType) VALUES("South German-Style Hefeweizen");
INSERT INTO style(styleType) VALUES("South German-Style Kristal Weizen");
INSERT INTO style(styleType) VALUES("German-Style Leichtes Weizen");
INSERT INTO style(styleType) VALUES("South German-Style Bernsteinfarbenes Weizen");
INSERT INTO style(styleType) VALUES("South German-Style Dunkel Weizen");
INSERT INTO style(styleType) VALUES("South German-Style Weizenbock");
INSERT INTO style(styleType) VALUES("German-Style Rye Ale");
INSERT INTO style(styleType) VALUES("Bamberg-Style Weiss Rauchbier");
INSERT INTO style(styleType) VALUES("Belgian-Style Blonde Ale");
INSERT INTO style(styleType) VALUES("Belgian-Style Pale Ale");
INSERT INTO style(styleType) VALUES("Belgian-Style Pale Strong Ale");
INSERT INTO style(styleType) VALUES("Belgian-Style Dark Strong Ale");
INSERT INTO style(styleType) VALUES("Belgian-Style Dubbel");
INSERT INTO style(styleType) VALUES("Belgian-Style Tripel");
INSERT INTO style(styleType) VALUES("Belgian-Style Quadrupel");
INSERT INTO style(styleType) VALUES("Belgian-Style Witbier");
INSERT INTO style(styleType) VALUES("Classic French & Belgian-Style Saison");
INSERT INTO style(styleType) VALUES("Specialty Saison");
INSERT INTO style(styleType) VALUES("French-Style Bière de Garde");
INSERT INTO style(styleType) VALUES("Belgian-Style Flanders Oud Bruin or Oud Red Ale");
INSERT INTO style(styleType) VALUES("Belgian-Style Lambic");
INSERT INTO style(styleType) VALUES("Belgian-Style Gueuze Lambic");
INSERT INTO style(styleType) VALUES("Belgian-Style Fruit Lambic");
INSERT INTO style(styleType) VALUES("Other Belgian-Style Ale");
INSERT INTO style(styleType) VALUES("Belgian-Style Table Beer");
INSERT INTO style(styleType) VALUES("Grodziskie");
INSERT INTO style(styleType) VALUES("Adambier");
INSERT INTO style(styleType) VALUES("Dutch-Style Kuit, Kuyt or Koyt");
INSERT INTO style(styleType) VALUES("Classic Australian-Style Pale Ale");
INSERT INTO style(styleType) VALUES("Australian-Style Pale Ale");
INSERT INTO style(styleType) VALUES("International-Style Pale Ale");
INSERT INTO style(styleType) VALUES("Finnish-Style Sahti");
INSERT INTO style(styleType) VALUES("Swedish-Style Gotlandsdricke");
INSERT INTO style(styleType) VALUES("Breslau-Style Pale Schoeps");
INSERT INTO style(styleType) VALUES("Breslau-Style Dark Schoeps");
INSERT INTO style(styleType) VALUES("German-Style Pilsener");
INSERT INTO style(styleType) VALUES("Bohemian-Style Pilsener");
INSERT INTO style(styleType) VALUES("Munich-Style Helles");
INSERT INTO style(styleType) VALUES("Dortmunder/European-Style Export");
INSERT INTO style(styleType) VALUES("Vienna-Style Lager");
INSERT INTO style(styleType) VALUES("German-Style Maerzen");
INSERT INTO style(styleType) VALUES("German-Style Oktoberfest/Wiesn");
INSERT INTO style(styleType) VALUES("Munich-Style Dunkel");
INSERT INTO style(styleType) VALUES("European-Style Dark Lager");
INSERT INTO style(styleType) VALUES("German-Style Schwarzbier");
INSERT INTO style(styleType) VALUES("German-Style Leichtbier");
INSERT INTO style(styleType) VALUES("Bamberg-Style Helles Rauchbier");
INSERT INTO style(styleType) VALUES("Bamberg-Style Maerzen Rauchbier");
INSERT INTO style(styleType) VALUES("Bamberg-Style Bock Rauchbier");
INSERT INTO style(styleType) VALUES("German-Style Heller Bock/Maibock");
INSERT INTO style(styleType) VALUES("Traditional German-Style Bock");
INSERT INTO style(styleType) VALUES("German-Style Doppelbock");
INSERT INTO style(styleType) VALUES("German-Style Eisbock");
INSERT INTO style(styleType) VALUES("Kellerbier or Zwickelbier Lager");
INSERT INTO style(styleType) VALUES("American-Style Lager");
INSERT INTO style(styleType) VALUES("American-Style Light Lager");
INSERT INTO style(styleType) VALUES("American-Style Amber Light Lager");
INSERT INTO style(styleType) VALUES("American-Style Pilsener");
INSERT INTO style(styleType) VALUES("Contemporary American-Style Pilsener");
INSERT INTO style(styleType) VALUES("American-Style Ice Lager");
INSERT INTO style(styleType) VALUES("American-Style Malt Liquor");
INSERT INTO style(styleType) VALUES("American-Style Amber Lager");
INSERT INTO style(styleType) VALUES("American-Style Maerzen/Oktoberfest");
INSERT INTO style(styleType) VALUES("American-Style Dark Lager");
INSERT INTO style(styleType) VALUES("Baltic-Style Porter");
INSERT INTO style(styleType) VALUES("Australasian, Latin American or Tropical-Style Light Lager");
INSERT INTO style(styleType) VALUES("International-Style Pilsener");
INSERT INTO style(styleType) VALUES("Session Beer");
INSERT INTO style(styleType) VALUES("American-Style Cream Ale");
INSERT INTO style(styleType) VALUES("California Common Beer");
INSERT INTO style(styleType) VALUES("Light American Wheat Beer with Yeast");
INSERT INTO style(styleType) VALUES("Light American Wheat Beer without Yeast");
INSERT INTO style(styleType) VALUES("Dark American Wheat Beer with Yeast");
INSERT INTO style(styleType) VALUES("Dark American Wheat Beer without Yeast");
INSERT INTO style(styleType) VALUES("American-Style Fruit Beer");
INSERT INTO style(styleType) VALUES("Fruit Wheat Beer");
INSERT INTO style(styleType) VALUES("Belgian-Style Fruit Beer");
INSERT INTO style(styleType) VALUES("Field Beer");
INSERT INTO style(styleType) VALUES("Pumpkin Spice Beer");
INSERT INTO style(styleType) VALUES("Pumpkin/Squash Beer");
INSERT INTO style(styleType) VALUES("Chocolate or Cocoa Beer");
INSERT INTO style(styleType) VALUES("Coffee Beer");
INSERT INTO style(styleType) VALUES("Chili Pepper Beer");
INSERT INTO style(styleType) VALUES("Herb and Spice Beer");
INSERT INTO style(styleType) VALUES("Specialty Beer");
INSERT INTO style(styleType) VALUES("Specialty Honey Beer");
INSERT INTO style(styleType) VALUES("Rye Beer");
INSERT INTO style(styleType) VALUES("Brett Beer");
INSERT INTO style(styleType) VALUES("Mixed-Culture Brett Beer");
INSERT INTO style(styleType) VALUES("Ginjo Beer or Sake-Yeast Beer");
INSERT INTO style(styleType) VALUES("Fresh Hop Beer");
INSERT INTO style(styleType) VALUES("Wood- and Barrel-Aged Beer");
INSERT INTO style(styleType) VALUES("Wood- and Barrel-Aged Pale to Amber Beer");
INSERT INTO style(styleType) VALUES("Wood- and Barrel-Aged Dark Beer");
INSERT INTO style(styleType) VALUES("Wood- and Barrel-Aged Strong Beer");
INSERT INTO style(styleType) VALUES("Wood- and Barrel-Aged Sour Beer");
INSERT INTO style(styleType) VALUES("Aged Beer");
INSERT INTO style(styleType) VALUES("Experimental Beer");
INSERT INTO style(styleType) VALUES("Historical Beer");
INSERT INTO style(styleType) VALUES("Wild Beer");
INSERT INTO style(styleType) VALUES("Smoke Beer");
INSERT INTO style(styleType) VALUES("Other Strong Ale or Lager");
INSERT INTO style(styleType) VALUES("Gluten-Free Beer");
INSERT INTO style(styleType) VALUES("Non-Alcoholic Malt Beverage");